FROM --platform=${BUILDPLATFORM} golang:1.21.1-bookworm AS build

ARG TARGETOS
ARG TARGETARCH

ENV GOOS=${TARGETOS}
ENV GOARCH=${TARGETARCH}
ENV CGO_ENABLED=0
RUN mkdir -p /go/src/github.com/fujiwara/greenlight
COPY . /go/src/github.com/fujiwara/greenlight
WORKDIR /go/src/github.com/fujiwara/greenlight
RUN make
RUN mkdir -p /opt/greenlight/bin
RUN touch /opt/greenlight/greenlight.yaml
RUN cp greenlight /opt/greenlight/bin/greenlight
